config/routes.rb
Spree::Core::Engine.routes.draw do
  match 'admin/create_business_cards/:id', :to => 'admin/products#create_business_cards', :as => :create_business_card
  match 'admin/update_business_cards/:id', :to => 'admin/products#update_business_cards', :as => :update_business_card
  match 'admin/new_business_cards', :to => 'admin/products#new_business_cards', :as => :new_business_card
  match 'admin/delete_business_cards/:id', :to => 'admin/products#delete_business_cards', :as => :delete_business_card

  namespace 'admin' do
    match 'retrieve_printer_format/:id', :to => 'printers#retrieve_printer_format'
    match 'calculate_convenience', :to => 'printers#calculate_convenience'
    match ':product_id/retrive_paper_weight/:paper_id/:id', :to => 'preventive#retrive_paper_weight'
    match ':product_id/retrive_paper/:id', :to => 'preventive#retrive_paper'
    match ':product_id/retrive_paper_weight_cover/:paper_id/:id', :to => 'preventive#retrive_paper_weight_cover'
    match ':product_id/retrive_paper_cover/:id', :to => 'preventive#retrive_paper_cover'
    match ':product_id/retrive_folding_format/:id', :to => 'preventive#retrive_folding_format'
    match 'precalculate', :to => 'preventive#precalculate'
    
    match 'paper/edit', :to => 'papers#edit', :as => :papers
    match 'hourly_costs/edit', :to => 'hourly_costs#edit', :as => :hourly_costs
    match 'cut/edit', :to => 'cut#edit', :as => :cut
    match 'hollow_punch/edit', :to => 'hollow_punch#edit', :as => :hollow_punch
    match 'plasticizations/edit', :to => 'plasticizations#edit', :as => :plasticizations
    match 'cutting_coil/edit', :to => 'cutting_coil#edit', :as => :cutting_coil
    match 'cutting_coil/:id', :to => 'cutting_coil#update', :as => :cutting_coil_update
    match 'lamination/edit', :to => 'lamination#edit', :as => :lamination
    match 'lamination/:id', :to => 'lamination#update', :as => :lamination_update
    match 'processing_plotter/edit', :to => 'processing_plotter#edit', :as => :processing_plotter
    match 'processing_plotter/:id', :to => 'processing_plotter#update', :as => :processing_plotter_update
    
    match 'edit_business_cards/:product_id/images/update/:id', :to => 'images#update', :as => :business_card_product_image

    match 'intercalations/', :to => 'intercalations#show', :as => :intercalations
    match 'intercalations/:intercalation_id/quantity/edit/:id', :to => 'intercalation_quantities#edit', :as => :edit_intercalation_quantities
    match 'intercalations/:intercalation_id/quantity:id', :to => 'intercalation_quantities#show', :as => :show_intercalation_quantities
    match 'intercalations/:intercalation_id/quantity/update/:id', :to => 'intercalation_quantities#update', :as => :update_intercalation_quantities

    match 'puncture/edit', :to => 'punctures#edit', :as => :punctures
    match 'puncture/update', :to => 'punctures#update', :as => :puncture_update
    match 'creasing/edit', :to => 'creasings#edit', :as => :creasings
    match 'creasing/update', :to => 'creasings#update', :as => :creasing_update
    
    match 'business_cards/edit/:id', :to => 'products#edit_business_cards', :as => :business_cards_edit
    match 'business_cards/:id/delete_template', :to => 'products#delete_template_business_cards', :as => :delete_template_business_card
    
    # Routing for Poster (MANIFESTO)
    match 'posters/edit/:id', :to => 'products#edit_posters', :as => :posters_edit
    match 'posters/update/:id', :to => 'products#update_posters', :as => :posters_update, :via => :put
    match 'posters/:product_id/images/update/:id', :to => 'images#update', :as => :poster_product_image
    # Routing for Poster Printer Format (FORMATI MANIFESTO)
    match 'posters/edit/:product_id/poster_printer_formats/index', :to => 'poster_printer_formats#index', :as => :poster_printer_formats_index
    match 'posters/edit/:product_id/poster_printer_formats/new', :to => 'poster_printer_formats#new', :as => :poster_printer_formats_new
    match 'posters/edit/:product_id/poster_printer_formats/create', :to => 'poster_printer_formats#create', :as => :poster_printer_formats_create
    match 'posters/edit/:product_id/poster_printer_formats/destroy/:id', :to => 'poster_printer_formats#destroy', :as => :poster_printer_formats_destroy
    match 'posters/edit/:product_id/poster_printer_formats/edit/:id', :to => 'poster_printer_formats#edit', :as => :poster_printer_formats_edit
    match 'posters/edit/:product_id/poster_printer_formats/update/:id', :to => 'poster_printer_formats#update', :as => :poster_printer_formats_update
    
    # Routing for PosterFlyer (MANIFESTO CLASSICO)
    match 'poster_flyers/edit/:id', :to => 'products#edit_poster_flyers', :as => :poster_flyers_edit
    match 'poster_flyers/update/:id', :to => 'products#update_poster_flyers', :as => :poster_flyers_update, :via => :put
    match 'poster_flyers/:product_id/images/update/:id', :to => 'images#update', :as => :poster_flyer_product_image
    # Routing for PosterFlyer Variant (FORMATI MANIFESTO CLASSICO)
    match 'poster_flyers/:poster_flyer_id/variants', :to => 'poster_flyer_variants#index', :as => :poster_flyer_variants
    match 'poster_flyers/:poster_flyer_id/variants/new', :to => 'poster_flyer_variants#new', :as => :new_poster_flyer_variants
    match 'poster_flyers/:poster_flyer_id/variants/create', :to => 'poster_flyer_variants#create', :as => :create_poster_flyer_variant
    match 'poster_flyers/:poster_flyer_id/variants/edit/:id', :to => 'poster_flyer_variants#edit', :as => :edit_poster_flyer_variant
    match 'poster_flyers/:poster_flyer_id/variants/update/:id', :to => 'poster_flyer_variants#update', :as => :update_poster_flyer_variant
    match 'poster_flyers/:poster_flyer_id/variants/:id', :to => 'poster_flyer_variants#destroy', :as => :delete_poster_flyer_variant, :method => :delete
    
    # Routing for Poster (MANIFESTO AD ALTISSIMA QUALITA)
    match 'poster_high_qualities/edit/:id', :to => 'products#edit_poster_high_qualities', :as => :poster_high_qualities_edit
    match 'poster_high_qualities/update/:id', :to => 'products#update_poster_high_qualities', :as => :poster_high_qualities_update, :via => :put
    match 'poster_high_qualities/:product_id/images/update/:id', :to => 'images#update', :as => :poster_high_quality_product_image
    # Routing for Poster Printer Format (FORMATI MANIFESTO AD ALTISSIMA QUALITA)
    match 'poster_high_qualities/edit/:product_id/poster_high_quality_printer_formats/index', :to => 'poster_high_quality_printer_formats#index', :as => :poster_high_quality_printer_formats_index
    match 'poster_high_qualities/edit/:product_id/poster_high_quality_printer_formats/new', :to => 'poster_high_quality_printer_formats#new', :as => :poster_high_quality_printer_formats_new
    match 'poster_high_qualities/edit/:product_id/poster_high_quality_printer_formats/create', :to => 'poster_high_quality_printer_formats#create', :as => :poster_high_quality_printer_formats_create
    match 'poster_high_qualities/edit/:product_id/poster_high_quality_printer_formats/destroy/:id', :to => 'poster_high_quality_printer_formats#destroy', :as => :poster_high_quality_printer_formats_destroy
    match 'poster_high_qualities/edit/:product_id/poster_high_quality_printer_formats/edit/:id', :to => 'poster_high_quality_printer_formats#edit', :as => :poster_high_quality_printer_formats_edit
    match 'poster_high_qualities/edit/:product_id/poster_high_quality_printer_formats/update/:id', :to => 'poster_high_quality_printer_formats#update', :as => :poster_high_quality_printer_formats_update
    
    # Routing for Flyer (FLYER)
    match 'flyers/edit/:id', :to => 'products#edit_flayers', :as => :flayers_edit
    match 'flyers/update/:id', :to => 'products#update_flayers', :as => :flayers_update, :via => :put
    match 'flyers/:product_id/images/update/:id', :to => 'images#update', :as => :flayer_product_image
    # Routing for Flyer Variant (FORMATI FLYER)
    match 'flyers/:flayer_id/variants', :to => 'flayer_variants#index', :as => :flayer_variants
    match 'flyers/:flayer_id/variants/new', :to => 'flayer_variants#new', :as => :new_flayer_variants
    match 'flyers/:flayer_id/variants/create', :to => 'flayer_variants#create', :as => :create_flayer_variant
    match 'flyers/:flayer_id/variants/edit/:id', :to => 'flayer_variants#edit', :as => :edit_flayer_variant
    match 'flyers/:flayer_id/variants/update/:id', :to => 'flayer_variants#update', :as => :update_flayer_variant
    match 'flyers/:flayer_id/variants/:id', :to => 'flayer_variants#destroy', :as => :delete_flayer_variant, :method => :delete
    
    # Routing for Letterhead (CARTA INTESTATA)
    match 'letterheads/edit/:id', :to => 'products#edit_letterheads', :as => :letterheads_edit
    match 'letterheads/update/:id', :to => 'products#update_letterheads', :as => :letterheads_update, :via => :put
    match 'letterheads/:product_id/images/update/:id', :to => 'images#update', :as => :letterhead_product_image
    # Routing for Letterhead Variant (FORMATI CARTA INTESTATA)
    match 'letterheads/:letterhead_id/variants', :to => 'letterhead_variants#index', :as => :letterhead_variants
    match 'letterheads/:letterhead_id/variants/new', :to => 'letterhead_variants#new', :as => :new_letterhead_variants
    match 'letterheads/:letterhead_id/variants/create', :to => 'letterhead_variants#create', :as => :create_letterhead_variant
    match 'letterheads/:letterhead_id/variants/edit/:id', :to => 'letterhead_variants#edit', :as => :edit_letterhead_variant
    match 'letterheads/:letterhead_id/variants/update/:id', :to => 'letterhead_variants#update', :as => :update_letterhead_variant
    match 'letterheads/:letterhead_id/variants/:id', :to => 'letterhead_variants#destroy', :as => :delete_letterhead_variant, :method => :delete
    
    # Routing for Playbill (LOCANDINE)
    match 'playbills/edit/:id', :to => 'products#edit_playbills', :as => :playbills_edit

app/models/spree/address_decorator.rb
Spree::Address.class_eval do
	_validators.reject!{ |key, value| (key == :firstname) || (key == :lastname) }
	_validate_callbacks.each do |callback|
		callback.raw_filter.attributes.reject! { |key| (key == :firstname) || (key == :lastname) } if callback.raw_filter.respond_to?(:attributes)
	end

	attr_accessor :is_company, :is_user
	attr_accessible :vat_number, :tax_id_number, :is_company

	validates :firstname, :lastname, :presence => true, :if => Proc.new {|a| a.company.blank? }
  validates :vat_number, :length => {:in => 8..16, :message => I18n.t(:vat_error)}, :if => Proc.new {|a| !a.vat_number.blank? }
  validates :tax_id_number, :length => {:in => 11..16}, :if => Proc.new {|a| !a.tax_id_number.blank? }
	before_validation :check_company_vat

	before_update :check_changed_address

	def check_changed_address
		if self.changed?
			user = Spree::User.find_by_bill_address_id(self.id)
			Spree::UserMailer.bill_change_email(self, user).deliver if Spree::Config[:notify_bill_user_change] && !user.blank?
		end
	end
	
	def check_company_vat
		unless(self.is_company.blank?)
			if(self.is_company != "0")
				self.firstname = ""
				self.lastname = ""
				self.tax_id_number = ""
			else
				self.company = ""
				self.vat_number = ""
				self.is_vies = false
			end
		end
	end

	def empty?
		attributes.except('id', 'created_at', 'updated_at', 'order_id', 'country_id', 'tax_id_number', 'vat_number').all? { |_, v| v.nil? }
	end

	def to_s
		"#{full_name} #{"<br />C.F.: " + tax_id_number if tax_id_number} #{"<br />P.IVA: "  + vat_number if vat_number}<br />Tel. #{phone}<br />#{address1} - #{zipcode}<br />#{city rescue nil}, (#{state_text}) [#{country.try(:name)}]".html_safe
	end

	def formatted
		"#{address1} - #{zipcode}, #{city rescue nil} - (#{state_text}) [#{country.try(:name)}]".html_safe
	end
	
	def to_ship
		"#{address1} #{address2 rescue nil} - #{zipcode}, #{city rescue nil} - (#{state_text}) [#{country.try(:name)}]".html_safe
	end

	def full_name
		rtn = self.company
		rtn = [self.firstname, self.lastname].join(' ') if rtn.blank?
		rtn = rtn.titleize if !rtn.blank?
		rtn
	end
end

app/models/spree/adjustment_decorator.rb
Spree::Adjustment.class_eval do
  scope :user_promotion, lambda { where(:originator_type => 'Spree::UserPromotion', :adjustable_type => 'Spree::LineItem') }
end

app/models/spree/advanced_product.rb
# Prodotto Avanzato
module Spree
  class AdvancedProduct < Product
	  has_many :advanced_variants, :class_name => Spree::AdvancedVariant, :foreign_key => "product_id", :dependent => :delete_all
	  has_many :simple_attributes, :class_name => "Spree::SimpleAttribute", :foreign_key => "variant_id", :dependent => :delete_all
    
    attr_accessible :marginality, :seo_title, :advanced_variants, :advanced_variants_attributes, :max_width,
                    :taxons, :taxon_ids, :simple_attributes, :simple_attributes_attributes
    
    after_create :setting_default_shipping_date
    
    accepts_nested_attributes_for :simple_attributes, :allow_destroy => true
    
    def accept_upload?
      self.max_width == 1
    end
    
    def ensure_master
      return unless new_record?
      self.master ||= Variant.new(:price => 0)
    end
    
    #def to_preventive
    #  self.advanced_variants.map{|av| av.entities.map{|e| ["id" => e.id, "model" => av.id, "attributes" => e.entity_attribute_values.map{|eav| Hash["id" => eav.attribute_id, 'pos' => eav.simple_attribute.position, "value" => Hash['id' => eav.value_id, 'pres' => eav.simple_value.presentation]]}.flatten]}}.flatten
    #end
    
    def to_preventive
      content = []
      self.advanced_variants.map do |av|
        acont = []
        self.simple_attributes.map do |sa|
          econt = []
          sa.entity_attribute_values.where("entity_id IN (#{av.entities.map{|e| e.id}.join(",")})").map do |eav|
            econt << {:id => eav.entity_id, :value_presentation => eav.simple_value.presentation, :value_id => eav.simple_value.id}
          end
          
          acont << {:id => sa.id, :position => sa.position, :name => sa.name, :entities => econt}
        end
        
        content << {:id => av.id, :attributes => acont}
      end
      
      content
    end
    
    def setting_default_shipping_date
      Spree::ShippingDateAdjustment.create(:name => "Ritiro di Base", :days => 2, :preferred_amount => 0, :product_id => self.id)
    end
	end
end

app/models/spree/advanced_variant.rb
# Variante Avanzata
module Spree
  class AdvancedVariant < Variant
    before_create :after_init
    belongs_to :advanced_product, :touch => true, :class_name => "Spree::AdvancedProduct", :foreign_key => "product_id"
    has_many :entities, :class_name => "Spree::Entity", :foreign_key => "variant_id", :dependent => :delete_all
    has_many :simple_attributes, :class_name => "Spree::SimpleAttribute", :foreign_key => "variant_id", :dependent => :delete_all
    
    attr_accessible :entities, :entities_attributes, :format, :simple_attributes, :simple_attributes_attributes
    
    accepts_nested_attributes_for :entities, :allow_destroy => true
    accepts_nested_attributes_for :simple_attributes, :allow_destroy => true

		alias_attribute :format, :sku

    private
    def after_init
      if self.new_record?
        self.active = true
        self.on_hand = 1
      end
    end
  end
end

app/models/spree/app_configuration_decorator.rb
#!/bin/env ruby
# encoding: utf-8

Spree::AppConfiguration.class_eval do
  preference :paper_weight, :string, :default => "80,90,100,110,115,120,130,140,150,160,170,200,215,230,240,250,280,300,350"
  
  preference :file_check, :boolean, :default => false
  preference :file_check_cost, :string, :default => "0.00"
  preference :file_check_desc, :string, :default => "Richiedi la verifica con operatore dei tuoi file per essere sicuro che siano corretti."
  
  preference :homepage_new_version_enabled, :boolean, :default => false
  preference :homepage_elements_number, :string, :default => "12"
  
  preference :privacy_description, :text, :default => "Acconsenti al trattamento dei dati personali"
  
  preference :order_notes, :text, :default => ""
	preference :cookie_law, :boolean, :default => false

	preference :notify_bill_user_change, :boolean, :default => false
	preference :notify_email, :string, :default => "admin@printtogo.it"
end

app/models/spree/banner_decorator.rb
Spree::Banner.class_eval do
  belongs_to :bannerable, :polymorphic => true
  
  attr_accessible :bannerable, :bannerable_id, :bannerable_type, :position
  
  def is_promotion?
    self.bannerable_type == "Spree::LineItemPromotion" && !self.bannerable_id.blank?
  end
  
  def promotion
    if self.is_promotion?
      Spree::LineItemPromotion.find(self.bannerable_id)
    else
      nil
    end
  end
end

app/models/spree/bending.rb
# PIEGATURA
module Spree
  class Bending < OptionValue
    after_save :associate_option_type
    belongs_to :bindery, :class_name => "Spree::Bindery", :foreign_key => "option_value_id"
    attr_accessible :type_quantity, :copy_cost, :start_time, :average_hourly_bending
    attr_accessor :_destroy
    
    def type_quantity
      self.presentation
    end
    
    def copy_cost
      self.start_time_bw
    end
    
    def start_time
      self.start_time_c
    end

    def average_hourly_bending
      self.average_hourly_print_c
    end
    
    def type_quantity=value
      self.presentation = value
    end
    
    def copy_cost=value
      self.start_time_bw = value
    end

    def start_time=value
      self.start_time_c = value
    end

    def average_hourly_bending=value
      self.average_hourly_print_c = value
    end

    private
    def associate_option_type
      self.update_attribute(:option_type_id, Spree::OptionType.find_by_name('bending').id) if self.option_type.nil?
    end
  end
end

app/models/spree/calculator/shipping_method_decorator.rb
Spree::ShippingMethod.class_eval do
  attr_accessible :min_weight,:max_weight
  validates :min_weight, :max_weight, :presence => true
end

app/views/spree/business_cards/_cart_form.html.erb
<%= javascript_include_tag 'store/preventive/business_card' %>
<% if @promo %>
<%= javascript_tag do %>
	$(function () {
		SetOptionPromotion(<%== @promo.to_calculate.to_json %>);
	});
<% end %>
<% end %>
<%= javascript_tag do %>
	printer_format_users = <%== @product.printer_format_cards_json %>;
	preventiveUrl = "<%= preventive_url %>";
	paper_products_selected = <%== @product.get_selected_values_json %>;
<% end %>

<%= form_for :order, {:url => populate_orders_url, :html => {:class => 'buy-form', :id => 'add_business_card'}} do |f| %>
    <%= hidden_field_tag(:business_card_product_id, @product.id) %>
	
    <h2>Formato</h2>
    <div class="format-check clearfix">
      <% first = true %>
      <% @product.printer_format_card_option_type.option_values.each do |ov| %>
          <div class="block f85x5">
            <div class="box"><%= ov.template_format.present? ? image_tag(ov.template_format.attachment.url(:normal)) : "" %></div>
            <%= radio_button_tag "order[format]", ov.id, first, {:class => 'radio', :id => "radio_format_#{ov.id }"} %>
            <% first = false %>
            <label for="radio_format_<%= ov.id %>"><%= ov.presentation %></label>
          </div>
      <% end %>
    </div>
    <% first = true %>
	
	<h2>Orientamento</h2>
    <div class="format-check">
      <% @product.directing_option_type.option_values.each do |ov| %>

          <div class="block <%= ov.presentation == 'Verticale' ? "vert" : "hor" %>">
            <div class="box"></div>
            <%= radio_button_tag "order[orientation]", ov.id, first, {:class => "radio", :id => "radio_orientation_#{ov.id}"} %>
            <% first = false %>
            <label for="radio_orientation_<%= "#{ov.id}" %>"><%= ov.presentation %></label>
          </div>

      <% end %>
    </div>

	<h2>Informazioni</h2>
	<label for="instructions">Indicazioni di stampa</label>
    <%= select("order", "instructions", [["Solo fronte","front"], ["Fronte e retro","front_back"]], {:include_blank => false}) %>
	
    <label for="paper">Carta</label>
    <select id="paper" name="order[paper]"></select>
	
    <label for="weight">Grammatura</label>
    <select id="weight" name="order[weight]"></select>

    <label for="plasticization">Plastificazione</label>
    <%= select_tag("order[plasticization]", options_for_select(Spree::Plasticization.standard), :prompt => 'Seleziona la plastificazione') %>

    <label for="print_color">Tipo stampa</label>
    <%= select("order", "print_color",[["Bianco e nero","false"], ["Colori","true"]] , {:include_blank => false}) %>

		<h2>Copie</h2>
		<label for="copy">Numero di copie</label>
		<% if !@product.number_of_copies.blank? %>
		<%= select("order", "number_of_copy", @product.number_of_copies.split(",").collect { |v| [v, v] }, {:include_blank => false, :prompt => "Seleziona quantita"}) %>
		<% else %>
		<%= text_field_tag("order[number_of_copy]", 0, :class => 'required', :min => @product.min_number_of_copies) %>
		<% end %>

<% if Spree::Config[:file_check] %>
	<h2><%= t(:file_check) %></h2>
	<label for="check"><%= t(:file_check) %></label>
	<%= select_tag("order[file_check]", options_for_select([["No", 0], ["Si", 1]])) %>
	<p style="padding: 0px; font-size: 12px; margin-bottom: 10px;" class="clearer"><%= "#{Spree::Config[:file_check_desc] } (#{Spree::Config[:file_check_cost]}&euro;)".html_safe %></p>
<% end %>

    <h2><%= t(:date_adjustment) %></h2>
    <%= render :partial => 'spree/shared/shipping_date_adjustment', :locals => {:product => @product} %>
	
	<%= render :partial => 'spree/shared/promotions', :locals => {:product => @product} %>
	
	<% if !Spree::Config[:order_notes].blank? %>
	<div class="note-box">
		<h4>Note Ordine</h4>
		<p><%= Spree::Config[:order_notes] %></p>
	</div>
	<% end %>

	<% unless @product.description2.blank? %>
	<div class="note-box2">
		<h4>Informazioni aggiuntive</h4>
		<p><%= raw(@product.description2) %></p>
	</div>
	<% end %>

    <%= hidden_field_tag :quantity, 1 %>
    <%= button_tag :class => 'btn-submit', :id => 'add-to-cart-button', :type => :submit do %>
        <%= content_tag(:span, t(:add_to_cart)) %>
    <% end %>
<% end %>

app/views/spree/business_cards/_image.html.erb
<% if image %>
  <%= image_tag image.attachment.url(:product), :itemprop => "image" %>
<% else %>
  <%= product_image(@product, :itemprop => "image") %>
<% end %>

app/views/spree/business_cards/_properties.html.erb
<% unless @product_properties.empty? %>
  <h6 class="product-section-title"><%= t('properties')%></h6>
  <table id="product-properties" class="table-display" data-hook width="100%">
    <tbody>
      <% for product_property in @product_properties
        css_class = cycle('even', 'odd') %>
        <tr class="<%= css_class %>">
          <td><strong><%= product_property.property.presentation %></strong></td>
          <td><%= product_property.value %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
<% end %>

app/views/spree/business_cards/_taxons.html.erb
<% if !@product.taxons.blank? %>
  <div id="taxon-crumbs" data-hook class="alpha columns five omega">
    <h6 class="product-section-title"><%= t(:look_for_similar_items) %></h6>

    <div data-hook="product_taxons">
      <ul id="similar_items_by_taxon" data-hook>
      <% @product.taxons.each do |taxon| %>
        <li><%= link_to taxon.name, seo_url(taxon) %></li>
      <% end %>
      </ul>
    </div>

  </div>
<% end %>

app/views/spree/business_cards/_thumbnails.html.erb
<!-- no need for thumnails unless there is more then one image -->
<% if product.images.size > 1 %>
  <ul id="product-thumbnails" class="thumbnails inline" data-hook>
    <% product.images.each do |i| %>
      <li class="tmb-all" id="tmb-<%= i.id.to_s %>"><%= link_to image_tag(i.attachment.url(:mini)), i.attachment.url(:product) %></li>
    <% end %>
    <% if @product.has_variants?
      @variants.each do |v|
        if v.available?
          v.images.each do |i| %>
            <li class="vtmb-<%= v.id.to_s %> vtmb" id="tmb-<%= i.id.to_s %>"><%= link_to image_tag(i.attachment.url(:mini)), i.attachment.url(:product) %></li>
          <%
          end
        end
      end
    end
    %>
  </ul>
<% end %>

app/views/spree/business_cards/show.html.erb
<div id="twocolumns" data-hook="product_show" itemscope itemtype="http://schema.org/Product">
	<% @body_id = 'product-details' %>
	<div id="content">
		<div class="content-box clearfix">
			<div class="clearfix left">
			<% if @product.images.empty? %>
				<%= image_tag 'store/img02.png', :width => 215 %>
			<% else %>
				<%= image_tag @product.images.first.attachment.url(:product), :width => 215 %>
			<% end %>
			</div>
			<div class="right">
				<%= breadcrumbs(@taxon, @product, @products) %>
				<h3><%= @product.name %></h3>
				<div class="desc_product_raw"><%= raw(@product.description) %></div>
			</div>
		</div>
		<%= render :partial => 'cart_form' %>
	</div>
	<div class="aside">
		<div id="fixed">
			<%= render :partial => 'spree/shared/total_order', :locals => {:order => current_order, :calculate_vat => true} %>
			<%= render :partial => 'spree/shared/preventive' %>
			<%= link_to("Scarica il tuo template", download_template_path(@product), :class => 'btn', :id => 'download_template') %>
		</div>
	</div>
</div>