config/routes.rb
Spree::Core::Engine.routes.draw do
  match 'admin/create_business_cards/:id', :to => 'admin/products#create_business_cards', :as => :create_business_card
  match 'admin/update_business_cards/:id', :to => 'admin/products#update_business_cards', :as => :update_business_card
  match 'admin/new_business_cards', :to => 'admin/products#new_business_cards', :as => :new_business_card
  match 'admin/delete_business_cards/:id', :to => 'admin/products#delete_business_cards', :as => :delete_business_card

  namespace 'admin' do
    match 'retrieve_printer_format/:id', :to => 'printers#retrieve_printer_format'
    match 'calculate_convenience', :to => 'printers#calculate_convenience'
    match ':product_id/retrive_paper_weight/:paper_id/:id', :to => 'preventive#retrive_paper_weight'
    match ':product_id/retrive_paper/:id', :to => 'preventive#retrive_paper'
    match ':product_id/retrive_paper_weight_cover/:paper_id/:id', :to => 'preventive#retrive_paper_weight_cover'
    match ':product_id/retrive_paper_cover/:id', :to => 'preventive#retrive_paper_cover'
    match ':product_id/retrive_folding_format/:id', :to => 'preventive#retrive_folding_format'
    match 'precalculate', :to => 'preventive#precalculate'
    
    match 'paper/edit', :to => 'papers#edit', :as => :papers
    match 'hourly_costs/edit', :to => 'hourly_costs#edit', :as => :hourly_costs
    match 'cut/edit', :to => 'cut#edit', :as => :cut
    match 'hollow_punch/edit', :to => 'hollow_punch#edit', :as => :hollow_punch
    match 'plasticizations/edit', :to => 'plasticizations#edit', :as => :plasticizations
    match 'cutting_coil/edit', :to => 'cutting_coil#edit', :as => :cutting_coil
    match 'cutting_coil/:id', :to => 'cutting_coil#update', :as => :cutting_coil_update
    match 'lamination/edit', :to => 'lamination#edit', :as => :lamination
    match 'lamination/:id', :to => 'lamination#update', :as => :lamination_update
    match 'processing_plotter/edit', :to => 'processing_plotter#edit', :as => :processing_plotter
    match 'processing_plotter/:id', :to => 'processing_plotter#update', :as => :processing_plotter_update
    
    match 'edit_business_cards/:product_id/images/update/:id', :to => 'images#update', :as => :business_card_product_image

    match 'intercalations/', :to => 'intercalations#show', :as => :intercalations
    match 'intercalations/:intercalation_id/quantity/edit/:id', :to => 'intercalation_quantities#edit', :as => :edit_intercalation_quantities
    match 'intercalations/:intercalation_id/quantity:id', :to => 'intercalation_quantities#show', :as => :show_intercalation_quantities
    match 'intercalations/:intercalation_id/quantity/update/:id', :to => 'intercalation_quantities#update', :as => :update_intercalation_quantities

    match 'puncture/edit', :to => 'punctures#edit', :as => :punctures
    match 'puncture/update', :to => 'punctures#update', :as => :puncture_update
    match 'creasing/edit', :to => 'creasings#edit', :as => :creasings
    match 'creasing/update', :to => 'creasings#update', :as => :creasing_update
    
    match 'business_cards/edit/:id', :to => 'products#edit_business_cards', :as => :business_cards_edit
    match 'business_cards/:id/delete_template', :to => 'products#delete_template_business_cards', :as => :delete_template_business_card
    
    # Routing for Poster (MANIFESTO)
    match 'posters/edit/:id', :to => 'products#edit_posters', :as => :posters_edit
    match 'posters/update/:id', :to => 'products#update_posters', :as => :posters_update, :via => :put
    match 'posters/:product_id/images/update/:id', :to => 'images#update', :as => :poster_product_image
    # Routing for Poster Printer Format (FORMATI MANIFESTO)
    match 'posters/edit/:product_id/poster_printer_formats/index', :to => 'poster_printer_formats#index', :as => :poster_printer_formats_index
    match 'posters/edit/:product_id/poster_printer_formats/new', :to => 'poster_printer_formats#new', :as => :poster_printer_formats_new
    match 'posters/edit/:product_id/poster_printer_formats/create', :to => 'poster_printer_formats#create', :as => :poster_printer_formats_create
    match 'posters/edit/:product_id/poster_printer_formats/destroy/:id', :to => 'poster_printer_formats#destroy', :as => :poster_printer_formats_destroy
    match 'posters/edit/:product_id/poster_printer_formats/edit/:id', :to => 'poster_printer_formats#edit', :as => :poster_printer_formats_edit
    match 'posters/edit/:product_id/poster_printer_formats/update/:id', :to => 'poster_printer_formats#update', :as => :poster_printer_formats_update
    
    # Routing for PosterFlyer (MANIFESTO CLASSICO)
    match 'poster_flyers/edit/:id', :to => 'products#edit_poster_flyers', :as => :poster_flyers_edit
    match 'poster_flyers/update/:id', :to => 'products#update_poster_flyers', :as => :poster_flyers_update, :via => :put
    match 'poster_flyers/:product_id/images/update/:id', :to => 'images#update', :as => :poster_flyer_product_image
    # Routing for PosterFlyer Variant (FORMATI MANIFESTO CLASSICO)
    match 'poster_flyers/:poster_flyer_id/variants', :to => 'poster_flyer_variants#index', :as => :poster_flyer_variants
    match 'poster_flyers/:poster_flyer_id/variants/new', :to => 'poster_flyer_variants#new', :as => :new_poster_flyer_variants
    match 'poster_flyers/:poster_flyer_id/variants/create', :to => 'poster_flyer_variants#create', :as => :create_poster_flyer_variant
    match 'poster_flyers/:poster_flyer_id/variants/edit/:id', :to => 'poster_flyer_variants#edit', :as => :edit_poster_flyer_variant
    match 'poster_flyers/:poster_flyer_id/variants/update/:id', :to => 'poster_flyer_variants#update', :as => :update_poster_flyer_variant
    match 'poster_flyers/:poster_flyer_id/variants/:id', :to => 'poster_flyer_variants#destroy', :as => :delete_poster_flyer_variant, :method => :delete
    
    # Routing for Poster (MANIFESTO AD ALTISSIMA QUALITA)
    match 'poster_high_qualities/edit/:id', :to => 'products#edit_poster_high_qualities', :as => :poster_high_qualities_edit
    match 'poster_high_qualities/update/:id', :to => 'products#update_poster_high_qualities', :as => :poster_high_qualities_update, :via => :put
    match 'poster_high_qualities/:product_id/images/update/:id', :to => 'images#update', :as => :poster_high_quality_product_image
    # Routing for Poster Printer Format (FORMATI MANIFESTO AD ALTISSIMA QUALITA)
    match 'poster_high_qualities/edit/:product_id/poster_high_quality_printer_formats/index', :to => 'poster_high_quality_printer_formats#index', :as => :poster_high_quality_printer_formats_index
    match 'poster_high_qualities/edit/:product_id/poster_high_quality_printer_formats/new', :to => 'poster_high_quality_printer_formats#new', :as => :poster_high_quality_printer_formats_new
    match 'poster_high_qualities/edit/:product_id/poster_high_quality_printer_formats/create', :to => 'poster_high_quality_printer_formats#create', :as => :poster_high_quality_printer_formats_create
    match 'poster_high_qualities/edit/:product_id/poster_high_quality_printer_formats/destroy/:id', :to => 'poster_high_quality_printer_formats#destroy', :as => :poster_high_quality_printer_formats_destroy
    match 'poster_high_qualities/edit/:product_id/poster_high_quality_printer_formats/edit/:id', :to => 'poster_high_quality_printer_formats#edit', :as => :poster_high_quality_printer_formats_edit
    match 'poster_high_qualities/edit/:product_id/poster_high_quality_printer_formats/update/:id', :to => 'poster_high_quality_printer_formats#update', :as => :poster_high_quality_printer_formats_update
    
    # Routing for Flyer (FLYER)
    match 'flyers/edit/:id', :to => 'products#edit_flayers', :as => :flayers_edit
    match 'flyers/update/:id', :to => 'products#update_flayers', :as => :flayers_update, :via => :put
    match 'flyers/:product_id/images/update/:id', :to => 'images#update', :as => :flayer_product_image
    # Routing for Flyer Variant (FORMATI FLYER)
    match 'flyers/:flayer_id/variants', :to => 'flayer_variants#index', :as => :flayer_variants
    match 'flyers/:flayer_id/variants/new', :to => 'flayer_variants#new', :as => :new_flayer_variants
    match 'flyers/:flayer_id/variants/create', :to => 'flayer_variants#create', :as => :create_flayer_variant
    match 'flyers/:flayer_id/variants/edit/:id', :to => 'flayer_variants#edit', :as => :edit_flayer_variant
    match 'flyers/:flayer_id/variants/update/:id', :to => 'flayer_variants#update', :as => :update_flayer_variant
    match 'flyers/:flayer_id/variants/:id', :to => 'flayer_variants#destroy', :as => :delete_flayer_variant, :method => :delete
    
    # Routing for Letterhead (CARTA INTESTATA)
    match 'letterheads/edit/:id', :to => 'products#edit_letterheads', :as => :letterheads_edit
    match 'letterheads/update/:id', :to => 'products#update_letterheads', :as => :letterheads_update, :via => :put
    match 'letterheads/:product_id/images/update/:id', :to => 'images#update', :as => :letterhead_product_image
    # Routing for Letterhead Variant (FORMATI CARTA INTESTATA)
    match 'letterheads/:letterhead_id/variants', :to => 'letterhead_variants#index', :as => :letterhead_variants
    match 'letterheads/:letterhead_id/variants/new', :to => 'letterhead_variants#new', :as => :new_letterhead_variants
    match 'letterheads/:letterhead_id/variants/create', :to => 'letterhead_variants#create', :as => :create_letterhead_variant
    match 'letterheads/:letterhead_id/variants/edit/:id', :to => 'letterhead_variants#edit', :as => :edit_letterhead_variant
    match 'letterheads/:letterhead_id/variants/update/:id', :to => 'letterhead_variants#update', :as => :update_letterhead_variant
    match 'letterheads/:letterhead_id/variants/:id', :to => 'letterhead_variants#destroy', :as => :delete_letterhead_variant, :method => :delete
    
    # Routing for Playbill (LOCANDINE)
    match 'playbills/edit/:id', :to => 'products#edit_playbills', :as => :playbills_edit

app/helpers/spree/admin/images_helper.rb
module Spree
  module Admin
    module ImagesHelper
      def retrive_path(product)
        if product.type == "Spree::BusinessCardProduct"
          admin_business_cards_edit_path
        elsif product.type == "Spree::PostersProduct"
          admin_posters_edit_path
        elsif product.type == "Spree::PosterFlyerProduct"
          admin_poster_flyers_edit_path
        elsif product.type == "Spree::PosterHighQualityProduct"
          admin_poster_high_qualities_edit_path
        elsif product.type == "Spree::FlayerProduct"
          admin_flayers_edit_path
        elsif product.type == "Spree::PlaybillProduct"
          admin_playbills_edit_path
        elsif product.type == "Spree::PostcardProduct"
          admin_postcards_edit_path
        elsif product.type == "Spree::LetterheadProduct"
          admin_letterheads_edit_path
        elsif product.type == "Spree::PaperbackProduct"
          admin_paperbacks_edit_path
        elsif product.type == "Spree::StapleProduct"
          admin_staples_edit_path
        elsif product.type == "Spree::BannerProduct"
          admin_banners_edit_path
        elsif product.type == "Spree::PvcProduct"
          admin_pvces_edit_path
        elsif product.type == "Spree::SpiralProduct"
          admin_spirals_edit_path
        elsif product.type == "Spree::CanvasProduct"
          admin_canvases_edit_path
        elsif product.type == "Spree::RigidProduct"
          admin_rigids_edit_path
        elsif product.type == "Spree::StickerProduct"
          admin_stickers_edit_path
        end
      end
    end
  end
end

app/views/spree/admin/images/_edit.html.erb
<% if @product.images.empty? %>
<h4><%= t(:new_image) %></h4>
<br />

	<%= form_tag("/admin/products/#{@product.permalink}/images", :html => { :multipart => true, :class => "well form-horizontal" })  do %>
	  <table class="basic-table" data-hook="new_image">
	    <%= render :partial => 'form' %>
	  </table>
	  <div class="form-actions" data-hook="buttons">
	    <%= button t(:update) %>
	    <%= t(:or) %> <%= link_to t(:cancel), admin_product_images_url(@product), :id => 'cancel_link' %>
	  </div>
	<% end %>
	<%= javascript_include_tag 'admin/images/new.js' %>
<% else %>
<h4><%= t(:edit_image) %></h4>
<br />

	<%= render :partial => 'spree/shared/error_messages', :locals => { :target => @product.images.first } %>

	<%= form_for([:admin, @product, @product.images.first], :html => { :multipart => true, :class => "well form-horizontal" }) do |f| %>
	  <table class="basic-table" data-hook="edit_image">
	    <tr data-hook="thumbnail">
	      <td><%= t(:thumbnail) %>:</td>
	      <td><%= link_to image_tag(@product.images.first.attachment.url(:mini)), @product.images.first.attachment.url(:product) %></td>
	    </tr>
	    <%= render :partial => 'form', :locals => { :f => f } %>
	  </table>
	  <div class="form-actions" data-hook="buttons">
	    <%= f.submit(t(:update), :class => "btn btn-info") %>
	    <%= t(:or) %> <%= link_to(t(:cancel), retrive_path(@product), :id => 'cancel_link', :class => "btn btn-danger") %>
	  </div>
	<% end %>
<% end %>

app/views/spree/admin/images/_form.html.erb
<%= content_tag(:label, t(:file_upload))%>
<%= file_field_tag  "image[attachment]" %>
<%= hidden_field_tag "product_id", @product.id %>
<%= hidden_field_tag "image[viewable_id]", "All" %>

app/views/spree/admin/images/_index.html.erb
<% if @product.images.empty? %>
<%= form_tag("/admin/products/#{@product.permalink}/images", :multipart => true, :class => "well") do %>
	<legend><%= t(:new_image) %></legend>
	<%= render :partial => 'form' %>
	<br class="clearer"/>
	<div class="form-actions right-txt">
		<%= submit_tag(t(:update), :class => "btn btn-primary") %>
	</div>
<% end %>
<%= javascript_include_tag 'admin/images/new.js' %>
<% else %>
<%= render :partial => 'spree/shared/error_messages', :locals => {:target => @product.images.first} %>
<%= form_for([:admin, @product, @product.images.first], :html => {:multipart => true, :class => "well clearfix"}) do |f| %>
	<legend><%= t(:edit_image) %></legend>
	<div class="span3 offset2">
		<%= link_to(image_tag(@product.images.first.attachment.url(:mini)), @product.images.first.attachment.url(:product), :class => "thumbnail") %>
	</div>
	<div class="span4">
		<%= render :partial => 'form' %>
	</div>
	<br class="clearer"/>
	<div class="form-actions right-txt">
		<%= f.submit(t(:update), :class => "btn btn-primary") %>
	</div>
<% end %>
<% end %>

app/views/spree/admin/images/_new.html.erb
<h4><%= t(:new_image) %></h4>
<%= form_tag "/admin/products/#{@product.permalink}/images", :multipart => true  do %>
  <table class="basic-table" data-hook="new_image">
    <%= render :partial => 'form' %>
  </table>
  <div class="form-actions" data-hook="buttons">
    <%= button t(:update) %>
    <%= t(:or) %> <%= link_to t(:cancel), admin_product_images_url(@product), :id => 'cancel_link' %>
  </div>
<% end %>

<%= javascript_include_tag 'admin/images/new.js' %>

app/views/spree/admin/images/create.js.erb
$("#images").html("<%= escape_javascript(render :partial => 'index') %>");

app/views/spree/admin/images/edit.js.erb
$('.loader').delay(200).fadeOut('slow', function() {
	$("#images").html("<%= escape_javascript(render :partial => 'edit') %>");
});

app/views/spree/admin/images/index.js.erb
$('.loader').delay(200).fadeOut('slow', function() {
	$("#images").html("<%= escape_javascript(render :partial => 'index') %>");
});

app/views/spree/admin/images/new.js.erb
if ($('.loader').length > 0) {
	$('.loader').delay(200).fadeOut('slow', function() {
		$("#images").html("<%= escape_javascript(render :partial => 'index') %>");
	});
} else {
	$("#images").html("<%= escape_javascript(render :partial => 'index') %>");
}

app/views/spree/admin/images/update.js.erb
$("#images").html("<%= escape_javascript(render :partial => 'index') %>");