config/routes.rb
Spree::Core::Engine.routes.draw do
  match 'admin/create_business_cards/:id', :to => 'admin/products#create_business_cards', :as => :create_business_card
  match 'admin/update_business_cards/:id', :to => 'admin/products#update_business_cards', :as => :update_business_card
  match 'admin/new_business_cards', :to => 'admin/products#new_business_cards', :as => :new_business_card
  match 'admin/delete_business_cards/:id', :to => 'admin/products#delete_business_cards', :as => :delete_business_card

  namespace 'admin' do
    match 'retrieve_printer_format/:id', :to => 'printers#retrieve_printer_format'
    match 'calculate_convenience', :to => 'printers#calculate_convenience'
    match ':product_id/retrive_paper_weight/:paper_id/:id', :to => 'preventive#retrive_paper_weight'
    match ':product_id/retrive_paper/:id', :to => 'preventive#retrive_paper'
    match ':product_id/retrive_paper_weight_cover/:paper_id/:id', :to => 'preventive#retrive_paper_weight_cover'
    match ':product_id/retrive_paper_cover/:id', :to => 'preventive#retrive_paper_cover'
    match ':product_id/retrive_folding_format/:id', :to => 'preventive#retrive_folding_format'
    match 'precalculate', :to => 'preventive#precalculate'
    
    match 'paper/edit', :to => 'papers#edit', :as => :papers
    match 'hourly_costs/edit', :to => 'hourly_costs#edit', :as => :hourly_costs
    match 'cut/edit', :to => 'cut#edit', :as => :cut
    match 'hollow_punch/edit', :to => 'hollow_punch#edit', :as => :hollow_punch
    match 'plasticizations/edit', :to => 'plasticizations#edit', :as => :plasticizations
    match 'cutting_coil/edit', :to => 'cutting_coil#edit', :as => :cutting_coil
    match 'cutting_coil/:id', :to => 'cutting_coil#update', :as => :cutting_coil_update
    match 'lamination/edit', :to => 'lamination#edit', :as => :lamination
    match 'lamination/:id', :to => 'lamination#update', :as => :lamination_update
    match 'processing_plotter/edit', :to => 'processing_plotter#edit', :as => :processing_plotter
    match 'processing_plotter/:id', :to => 'processing_plotter#update', :as => :processing_plotter_update
    
    match 'edit_business_cards/:product_id/images/update/:id', :to => 'images#update', :as => :business_card_product_image

    match 'intercalations/', :to => 'intercalations#show', :as => :intercalations
    match 'intercalations/:intercalation_id/quantity/edit/:id', :to => 'intercalation_quantities#edit', :as => :edit_intercalation_quantities
    match 'intercalations/:intercalation_id/quantity:id', :to => 'intercalation_quantities#show', :as => :show_intercalation_quantities
    match 'intercalations/:intercalation_id/quantity/update/:id', :to => 'intercalation_quantities#update', :as => :update_intercalation_quantities

    match 'puncture/edit', :to => 'punctures#edit', :as => :punctures
    match 'puncture/update', :to => 'punctures#update', :as => :puncture_update
    match 'creasing/edit', :to => 'creasings#edit', :as => :creasings
    match 'creasing/update', :to => 'creasings#update', :as => :creasing_update
    
    match 'business_cards/edit/:id', :to => 'products#edit_business_cards', :as => :business_cards_edit
    match 'business_cards/:id/delete_template', :to => 'products#delete_template_business_cards', :as => :delete_template_business_card
    
    # Routing for Poster (MANIFESTO)
    match 'posters/edit/:id', :to => 'products#edit_posters', :as => :posters_edit
    match 'posters/update/:id', :to => 'products#update_posters', :as => :posters_update, :via => :put
    match 'posters/:product_id/images/update/:id', :to => 'images#update', :as => :poster_product_image
    # Routing for Poster Printer Format (FORMATI MANIFESTO)
    match 'posters/edit/:product_id/poster_printer_formats/index', :to => 'poster_printer_formats#index', :as => :poster_printer_formats_index
    match 'posters/edit/:product_id/poster_printer_formats/new', :to => 'poster_printer_formats#new', :as => :poster_printer_formats_new
    match 'posters/edit/:product_id/poster_printer_formats/create', :to => 'poster_printer_formats#create', :as => :poster_printer_formats_create
    match 'posters/edit/:product_id/poster_printer_formats/destroy/:id', :to => 'poster_printer_formats#destroy', :as => :poster_printer_formats_destroy
    match 'posters/edit/:product_id/poster_printer_formats/edit/:id', :to => 'poster_printer_formats#edit', :as => :poster_printer_formats_edit
    match 'posters/edit/:product_id/poster_printer_formats/update/:id', :to => 'poster_printer_formats#update', :as => :poster_printer_formats_update
    
    # Routing for PosterFlyer (MANIFESTO CLASSICO)
    match 'poster_flyers/edit/:id', :to => 'products#edit_poster_flyers', :as => :poster_flyers_edit
    match 'poster_flyers/update/:id', :to => 'products#update_poster_flyers', :as => :poster_flyers_update, :via => :put
    match 'poster_flyers/:product_id/images/update/:id', :to => 'images#update', :as => :poster_flyer_product_image
    # Routing for PosterFlyer Variant (FORMATI MANIFESTO CLASSICO)
    match 'poster_flyers/:poster_flyer_id/variants', :to => 'poster_flyer_variants#index', :as => :poster_flyer_variants
    match 'poster_flyers/:poster_flyer_id/variants/new', :to => 'poster_flyer_variants#new', :as => :new_poster_flyer_variants
    match 'poster_flyers/:poster_flyer_id/variants/create', :to => 'poster_flyer_variants#create', :as => :create_poster_flyer_variant
    match 'poster_flyers/:poster_flyer_id/variants/edit/:id', :to => 'poster_flyer_variants#edit', :as => :edit_poster_flyer_variant
    match 'poster_flyers/:poster_flyer_id/variants/update/:id', :to => 'poster_flyer_variants#update', :as => :update_poster_flyer_variant
    match 'poster_flyers/:poster_flyer_id/variants/:id', :to => 'poster_flyer_variants#destroy', :as => :delete_poster_flyer_variant, :method => :delete
    
    # Routing for Poster (MANIFESTO AD ALTISSIMA QUALITA)
    match 'poster_high_qualities/edit/:id', :to => 'products#edit_poster_high_qualities', :as => :poster_high_qualities_edit
    match 'poster_high_qualities/update/:id', :to => 'products#update_poster_high_qualities', :as => :poster_high_qualities_update, :via => :put
    match 'poster_high_qualities/:product_id/images/update/:id', :to => 'images#update', :as => :poster_high_quality_product_image
    # Routing for Poster Printer Format (FORMATI MANIFESTO AD ALTISSIMA QUALITA)
    match 'poster_high_qualities/edit/:product_id/poster_high_quality_printer_formats/index', :to => 'poster_high_quality_printer_formats#index', :as => :poster_high_quality_printer_formats_index
    match 'poster_high_qualities/edit/:product_id/poster_high_quality_printer_formats/new', :to => 'poster_high_quality_printer_formats#new', :as => :poster_high_quality_printer_formats_new
    match 'poster_high_qualities/edit/:product_id/poster_high_quality_printer_formats/create', :to => 'poster_high_quality_printer_formats#create', :as => :poster_high_quality_printer_formats_create
    match 'poster_high_qualities/edit/:product_id/poster_high_quality_printer_formats/destroy/:id', :to => 'poster_high_quality_printer_formats#destroy', :as => :poster_high_quality_printer_formats_destroy
    match 'poster_high_qualities/edit/:product_id/poster_high_quality_printer_formats/edit/:id', :to => 'poster_high_quality_printer_formats#edit', :as => :poster_high_quality_printer_formats_edit
    match 'poster_high_qualities/edit/:product_id/poster_high_quality_printer_formats/update/:id', :to => 'poster_high_quality_printer_formats#update', :as => :poster_high_quality_printer_formats_update
    
    # Routing for Flyer (FLYER)
    match 'flyers/edit/:id', :to => 'products#edit_flayers', :as => :flayers_edit
    match 'flyers/update/:id', :to => 'products#update_flayers', :as => :flayers_update, :via => :put
    match 'flyers/:product_id/images/update/:id', :to => 'images#update', :as => :flayer_product_image
    # Routing for Flyer Variant (FORMATI FLYER)
    match 'flyers/:flayer_id/variants', :to => 'flayer_variants#index', :as => :flayer_variants
    match 'flyers/:flayer_id/variants/new', :to => 'flayer_variants#new', :as => :new_flayer_variants
    match 'flyers/:flayer_id/variants/create', :to => 'flayer_variants#create', :as => :create_flayer_variant
    match 'flyers/:flayer_id/variants/edit/:id', :to => 'flayer_variants#edit', :as => :edit_flayer_variant
    match 'flyers/:flayer_id/variants/update/:id', :to => 'flayer_variants#update', :as => :update_flayer_variant
    match 'flyers/:flayer_id/variants/:id', :to => 'flayer_variants#destroy', :as => :delete_flayer_variant, :method => :delete
    
    # Routing for Letterhead (CARTA INTESTATA)
    match 'letterheads/edit/:id', :to => 'products#edit_letterheads', :as => :letterheads_edit
    match 'letterheads/update/:id', :to => 'products#update_letterheads', :as => :letterheads_update, :via => :put
    match 'letterheads/:product_id/images/update/:id', :to => 'images#update', :as => :letterhead_product_image
    # Routing for Letterhead Variant (FORMATI CARTA INTESTATA)
    match 'letterheads/:letterhead_id/variants', :to => 'letterhead_variants#index', :as => :letterhead_variants
    match 'letterheads/:letterhead_id/variants/new', :to => 'letterhead_variants#new', :as => :new_letterhead_variants
    match 'letterheads/:letterhead_id/variants/create', :to => 'letterhead_variants#create', :as => :create_letterhead_variant
    match 'letterheads/:letterhead_id/variants/edit/:id', :to => 'letterhead_variants#edit', :as => :edit_letterhead_variant
    match 'letterheads/:letterhead_id/variants/update/:id', :to => 'letterhead_variants#update', :as => :update_letterhead_variant
    match 'letterheads/:letterhead_id/variants/:id', :to => 'letterhead_variants#destroy', :as => :delete_letterhead_variant, :method => :delete
    
    # Routing for Playbill (LOCANDINE)
    match 'playbills/edit/:id', :to => 'products#edit_playbills', :as => :playbills_edit

app/models/spree/folding.rb
# PIEGATURA
module Spree
  class Folding < OptionValue
    after_save :associate_option_type
    after_update :update_variant
    
    has_many :folding_weights, :class_name => "Spree::FoldingWeight", :foreign_key => "option_value_id", :dependent => :nullify
    has_many :folding_formats, :class_name => "Spree::FoldingFormat", :foreign_key => "option_value_id", :dependent => :delete_all

    attr_accessible :name, :hourly_cost, :folding_weights_attributes, :folding_weights, :start_time, :active,
                    :plastification, :average_hourly_plastification, :external, :min_limit_folding, :cost_folding,
                    :copy_cost_plastification

    validates :name, :presence => true

    accepts_nested_attributes_for :folding_weights, :allow_destroy => true
    
    scope :active, lambda { where("active IS NOT NULL AND active = 1") }
    
    def plastification
      self.is_cut
    end
    
    def external
      self.copy_cost_seam
    end
    
    def average_hourly_plastification
      self.average_hourly_print_c
    end
    
    def copy_cost_plastification
      self.average_hourly_print_bw
    end
    
    def hourly_cost
      self.start_up_cost_c
    end

    def start_time
      self.start_up_cost_bw
    end
    
    def cost_folding
      self.plant_color_bw
    end

    def min_limit_folding
      self.plant_color_c
    end
    
    def plastification= value
      self.is_cut = value
    end
    
    def external= value
      self.copy_cost_seam = value
    end
    
    def average_hourly_plastification= value
      self.average_hourly_print_c = value
    end
    
    def copy_cost_plastification= value
      self.average_hourly_print_bw = value
    end
    
    def hourly_cost= value
      self.start_up_cost_c = value
    end
    
    def start_time= value
      self.start_up_cost_bw = value
    end
    
    def cost_folding= value
      self.plant_color_bw = value
    end

    def min_limit_folding= value
      self.plant_color_c = value
    end
    
    def update_variant
      if !active
        tmp = Spree::FoldingFormat.find_all_by_option_value_id(self.id)
        if !tmp.empty?
          Spree::FoldingFormat.delete_all("option_value_id = #{self.id}")
        end
      else
        tmp = Spree::FoldingFormat.find_all_by_option_value_id(self.id)
        if tmp.empty?
          Spree::FoldingVariant.all.each do |fv|
            ff = Spree::FoldingFormat.create(:option_value_id => self.id, :variant_id => fv.id)
            ff.generate_paper_products
            fv.option_values << ff
          end
        end
      end
    end
    
    private
    def associate_option_type
      self.update_attribute(:option_type_id, Spree::OptionType.find_by_name('folding').id) if self.option_type.nil?
    end
  end
end

app/controllers/spree/admin/foldings_controller.rb
module Spree
  module Admin
    class FoldingsController < Spree::Admin::BaseController
      def index
        @foldings = Spree::Folding.all
      end

      def update
        @folding = Spree::Folding.find(params[:id])
        @folding.update_attributes(params[:folding])
        if @folding.folding_weights.empty?
          @folding.update_attribute(:active, false)
        end
        
        flash[:notice] = t(:edit_success)
        redirect_to :action => :edit
      end

      def edit
        @folding = Spree::Folding.find(params[:id])
      end

      def destroy
        @folding = Spree::Folding.find(params[:id])
        @folding.destroy
        #flash[:notice] = t(:delete_success)
        #redirect_to :action => :index
        respond_to do |format|
          format.html {redirect_to :action => :index}
          format.js {render :layout => false}
        end
      end

      def new
        @folding = Spree::Folding.new
      end

      def create
        @folding = Spree::Folding.new(params[:folding])
        @folding.save
        
        flash[:notice] = t(:create_success)
        redirect_to :action => :edit
      end
    end
  end
end

app/controllers/spree/foldings_controller.rb
module Spree
  class FoldingsController < BaseController
    before_filter :load_product, :only => :show
    rescue_from ActiveRecord::RecordNotFound, :with => :render_root
    helper 'spree/taxons'

    respond_to :html

    def load_product
      @product = Spree::FoldingProduct.active.find_by_permalink!(params[:id])
      @promotions = Spree::LineItemPromotion.active.available.find_all_by_product_id(@product.id)
    end
    
    def show
      return unless @product
      @title = @product.seo_title
      @promo = getPromotion(@product, params[:promo_code])
      @variants = @product.folding_variants.active.includes([:option_values, :images]).where(:product_id => @product.id, :active => true)
      
      respond_with(@product, @promo)
    end
    
    def retrieve_folding_paper_weight
      render :json => Spree::FoldingFormat.find_by_option_value_id_and_variant_id(params[:folding_id], params[:id]).get_paper_weight
    end    
  end
end

app/views/spree/admin/foldings/_folding_weight_efields.html.erb
<div class="fields clearfix">
	<div class="control-group span3">
		<%= label_tag(:copy_cost, t(:copy_cost), :class => "control-label left-txt padding-label-left") %>
		<div class="controls">
	  		<%= f.text_field(:copy_cost) %>
		</div>
	</div>
	<div class="control-group span3">
		<%= label_tag(:weight_limit, t(:weight_limit), :class => "control-label left-txt padding-label-left") %>
		<div class="controls">
	  		<%= f.select(:weight_limit, Spree::Config[:paper_weight].split(",").map {|w| ["Fino a #{w} Gr.", w]}, :prompt => true, :selected => f.object.weight_limit.to_i) %>
		</div>
	</div>
	<div class="control-label span3" style="margin-top: 30px;">
		<%= link_to_confirm_remove_fields("Rimuovi Grammatura", f) %>
	</div>
	<br class="clearer"/>
</div>

app/views/spree/admin/foldings/_folding_weight_fields.html.erb
<div class="fields clearfix">
	<div class="span3">
		<%= label_tag(:average_hourly, t(:average_hourly)) %>
	  	<%= f.text_field(:average_hourly) %>
	</div>
	<div class="span3">
		<%= label_tag(:weight_limit, t(:weight_limit)) %>
	  	<%= f.select(:weight_limit, Spree::Config[:paper_weight].split(",").map {|w| ["Fino a #{w} Gr.", w]}, :prompt => true, :selected => f.object.weight_limit.to_i) %>
	</div>
	<div class="span3" style="margin-top: 30px;">
		<%= link_to_confirm_remove_fields("Rimuovi Grammatura", f) %>
	</div>
</div>
<br class="clearer"/>

app/views/spree/admin/foldings/_form.html.erb
<div class="clearfix">
	<div class="span4">
		<label class="checkbox">
			<%= f.check_box(:active, :value => @folding.active) %> <%= t(:active) %>
		</label>
	</div>
	<div class="span4">
		<label class="checkbox">
			<%= f.check_box(:plastification, :value => @folding.plastification) %>	<%= t(:plastification) %>
		</label>
	</div>
	<div class="span4">
	    <label class="checkbox">
			<%= f.check_box(:external, :value => @folding.external) %> <%= t(:external) %>
		</label>
		<p class="small" style="font-size: 11px; color: #880000;">Occorre salvare per poter visualizzare la modifica</p>
	</div>
</div>
<% if !@folding.external %>
<div id="internal">
	<legend class="small">Costi Orari per le lavorazioni</legend>
	<div class="span3">
		<%= label_tag(:hourly_cost, t(:hourly_cost)) %>
		<%= f.text_field :hourly_cost %>
	</div>
	<div class="span3">
		<%= label_tag(:start_time, t(:start_time)) %>
		<%= f.text_field :start_time %>
	</div>
	<div class="span4" id="average_hourly_plastification">
		<%= label_tag(:average_hourly_plastification, t(:average_hourly_plastification), :class => "left-txt padding-label-left") %>
		<%= f.text_field :average_hourly_plastification %>
	</div>
	<div class="span15">
		<%= f.fields_for :folding_weights do |builder| %>
		<%= render "folding_weight_fields", :f => builder %>
		<% end %>
		<p class="small"><%= link_to_add_fields("Aggiungi una nuova grammatura", f, :folding_weights) %></p>
	</div>
</div>
<% else %>
<div id="external">
	<legend class="small">Costi Orari per le lavorazioni</legend>
	<br class="clearer"/>
	<div class="span3">
		<%= label_tag(:cost_folding, t(:cost_folding)) %>
		<%= f.text_field :cost_folding %>
	</div>
	<div class="control-group span3">
		<%= label_tag(:min_limit_folding, t(:min_limit_folding)) %>
		<%= f.text_field :min_limit_folding %>
	</div>
	<div class="span4" id="copy_cost_plastification" style="display: none;">
	    <%= label_tag(:copy_cost_plastification, t(:copy_cost_plastification)) %>
		<%= f.text_field :copy_cost_plastification %>
	</div>
	<br class="clearer"/>
	<div class="span15">
		<%= f.fields_for :folding_weights do |builder| %>
		<%= render "folding_weight_efields", :f => builder %>
		<% end %>
		<p class="small"><%= link_to_add_efields("Aggiungi una nuova grammatura", f, :folding_weights) %></p>
	</div>
</div>
<% end %>

app/views/spree/admin/foldings/edit.html.erb
<div class="row">
	<div class="span16">
		<h2><%= t(:edit) %> <%= t(:folding) %></h2>
		<%= form_for([:admin, @folding], :url => {:action => :update}, :html => {:class => "well"}) do |f| %>
			<legend><%= @folding.name %></legend>
		    <%=  render :partial => 'form', :locals => {:f => f} %>
		    <div class="form-actions clearer right-txt">
				<%= f.submit(t(:update), :class => "btn btn-primary") %>
		      	<%= link_to(t(:back), admin_foldings_path, :class => "btn btn-inverse") %>
		    </div>
		<% end %>
	</div>
</div>

<%= javascript_tag do %>
	if ($("#folding_plastification").is(":checked")) {
		if ($("#folding_external").is(":checked")) {
			$("#copy_cost_plastification").show();
		} else {
			$("#average_hourly_plastification").show();
		}
	} else {
		if ($("#folding_external").is(":checked")) {
			$("#copy_cost_plastification").hide();
			$("#copy_cost_plastification").find("input").val(0);
		} else {
			$("#average_hourly_plastification").hide();
			$("#average_hourly_plastification").find("input").val(0);
		}
	}
	
	$("#folding_plastification").change(function() {
		if ($(this).is(":checked")) {
			if ($("#folding_external").is(":checked")) {
				$("#copy_cost_plastification").show();
			} else {
				$("#average_hourly_plastification").show();
			}
		} else {
			if ($("#folding_external").is(":checked")) {
				$("#copy_cost_plastification").hide();
				$("#copy_cost_plastification").find("input").val(0);
			} else {
				$("#average_hourly_plastification").hide();
				$("#average_hourly_plastification").find("input").val(0);
			}
		}
	});
	
	
	if ($("#folding_external").is(":checked")) {
		if ($("#folding_plastification").is(":checked")) {
			$("#copy_cost_plastification").show();
		} else {
			$("#copy_cost_plastification").hide();
			$("#copy_cost_plastification").find("input").val(0);
		}
			
	} else {
		if ($("#folding_plastification").is(":checked")) {
			$("#average_hourly_plastification").show();
		} else {
			$("#average_hourly_plastification").hide();
			$("#average_hourly_plastification").find("input").val(0);
		}
	}
	$("#folding_external").change(function() {
		if ($(this).is(":checked")) {
			if ($("#folding_plastification").is(":checked")) {
				$("#copy_cost_plastification").show();
			} else {
				$("#copy_cost_plastification").hide();
				$("#copy_cost_plastification").find("input").val(0);
			}
		} else {
			if ($("#folding_plastification").is(":checked")) {
				$("#average_hourly_plastification").show();
			} else {
				$("#average_hourly_plastification").hide();
				$("#average_hourly_plastification").find("input").val(0);
			}
		}
	});
<% end %>

app/views/spree/admin/foldings/index.html.erb
<% @body_id = "folding" %>

<div class="row">
	<div class="span7">
		<h2><%= t(:foldings) %></h2>
		<p>In questa pagina puoi gestire le opzioni di piegatura</p>
	</div>
	<div class="span8 content-box margin-top">
		In questa sezione potrete configurare i tipi di piega comunemente usati per i depliant.
		Per ogni tipo di piega dovrete impostare:
		<ol>
			<li>attivo o non attivo</li>
			<li>se la tipologia di piega viene plastificata e nel caso affermativo dovrete inserire la relativa media oraria</li>
			<li>impostare se la lavorazione avverr&agrave; in esterna o in interna</li>
			<li>potrete inserire i vari costi fissi o variabili per le macchine utilizzate</li>
			<li>infine dovrete impostare i vari limiti di costo per grammatura</li>
		</ol>
	</div>
	<br class="clearer"/><br />
	
	<div class="span16">
		<table class="table table-condensed table-bordered">
			<thead>
				<tr data-hook="admin_users_index_headers" class="info">
					<th><%= t(:fold_type) %></th>
					<th><%= t(:limit_set) %></th>
					<th><%= t(:active) %></th>
					<th data-hook="admin_foldings_index_header_actions"></th>
				</tr>
			</thead>
			<% @foldings.each do |folding| %>
			<tbody>
				<tr id="folding_<%= folding.id %>">
					<td style="vertical-align: middle;"><%= folding.name %></td>
					<td><%= raw folding.folding_weights.collect {|fw| content_tag(:span, "Fino a #{fw.weight_limit.to_i} Gr. => #{fw.average_hourly.to_i} cp/ora", :class => "label label-inverse") }.join(" ") %></td>
					<td style="vertical-align: middle;"><%= (folding.active) ? content_tag(:span, "Attiva <i class='icon-ok icon-white'></i>".html_safe, :class => "label label-success") : content_tag(:span, "Disattiva <i class='icon-off icon-white'></i>".html_safe, :class => "label label-warning") %></td>
					<td class='actions' data-hook="admin_foldings_index_row_actions">
						<%= link_to("Modifica <i class='icon-edit icon-white'></i>".html_safe, edit_admin_folding_path(folding), :class => "btn btn-primary") %>
					</td>
				</tr>
			</tbody>
			<% end %>
		</table>
	</div>
</div>

app/views/spree/admin/foldings/new.html.erb
<h2><%= t(:create) %> <%= t(:folding) %></h2>
<br />
<%= form_for([:admin, @folding], :url => {:action => :create}, :html => {:class => "well form-horizontal clearfix"}) do |f| %>
	<%=  render :partial => 'form', :locals => {:f => f} %>
	<div class="form-actions clearer">
		<%= f.submit(t(:create), :class => "btn btn-info btn-large right") %>
      	<%= link_to(t(:back), admin_foldings_path, :class => "btn btn-inverse right", :style => "margin-right: 10px") %>
    </div>
<% end %>
<%= javascript_tag do %>
	if ($("#folding_plastification").is(":checked")) {
		if ($("#folding_external").is(":checked")) {
			$("#copy_cost_plastification").show();
		} else {
			$("#average_hourly_plastification").show();
		}
	} else {
		if ($("#folding_external").is(":checked")) {
			$("#copy_cost_plastification").hide();
			$("#copy_cost_plastification").find("input").val(0);
		} else {
			$("#average_hourly_plastification").hide();
			$("#average_hourly_plastification").find("input").val(0);
		}
	}
	
	$("#folding_plastification").change(function() {
		if ($(this).is(":checked")) {
			if ($("#folding_external").is(":checked")) {
				$("#copy_cost_plastification").show();
			} else {
				$("#average_hourly_plastification").show();
			}
		} else {
			if ($("#folding_external").is(":checked")) {
				$("#copy_cost_plastification").hide();
				$("#copy_cost_plastification").find("input").val(0);
			} else {
				$("#average_hourly_plastification").hide();
				$("#average_hourly_plastification").find("input").val(0);
			}
		}
	});
	
	
	if ($("#folding_external").is(":checked")) {
		$("#external").show();
		$("#internal").hide();
		if ($("#folding_plastification").is(":checked")) {
			$("#copy_cost_plastification").show();
		} else {
			$("#copy_cost_plastification").hide();
			$("#copy_cost_plastification").find("input").val(0);
		}
			
	} else {
		$("#external").hide();
		$("#internal").show();
		if ($("#folding_plastification").is(":checked")) {
			$("#average_hourly_plastification").show();
		} else {
			$("#average_hourly_plastification").hide();
			$("#average_hourly_plastification").find("input").val(0);
		}
	}
	$("#folding_external").change(function() {
		if ($(this).is(":checked")) {
			$("#internal").hide();
			$("#external").show();
			if ($("#folding_plastification").is(":checked")) {
				$("#copy_cost_plastification").show();
			} else {
				$("#copy_cost_plastification").hide();
				$("#copy_cost_plastification").find("input").val(0);
			}
		} else {
			$("#external").hide();
			$("#internal").show();
			if ($("#folding_plastification").is(":checked")) {
				$("#average_hourly_plastification").show();
			} else {
				$("#average_hourly_plastification").hide();
				$("#average_hourly_plastification").find("input").val(0);
			}
		}
	});
<% end %>